version: '3.8'

services:
  node-app:
    build: .
    image: jwt-socket
    environment:
      - DB_URL=mongodb://mongo-local:27017
      - PORT=8080
    ports:
      - '80:8080'
    depends_on:
      - mongo-local
    volumes:
      - .:/src
    networks:
      - node-network

  mongo-local:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge